# Generated by Django 3.1 on 2020-08-14 08:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Статья')),
                ('content', ckeditor.fields.RichTextField(max_length=3000, verbose_name='Текст статьи')),
                ('pub_date', models.DateField(auto_now=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(upload_to='media/uploads/', verbose_name='Изображение статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('pub_date',),
            },
        ),
    ]
